x-common: &common
  restart: always
  logging:
    options:
      max-size: "1m"
      max-file: "1"

x-atlassian-env: &atlassian-env
  environment:
  - TZ=Asia/Bangkok
  - JVM_MINIMUM_MEMORY=2g
  - JVM_MAXIMUM_MEMORY=4g

services:
  confluence:
    <<: [*common, *atlassian-env]
    build: .
    ports:
      - "8090:8090"
    volumes:
      - ./data/confluence:/var/confluence
      - ./confluence/server.xml:/opt/confluence/conf/server.xml
      - ./confluence/setenv.sh:/opt/confluence/bin/setenv.sh
      - ./confluence/atlassian-agent.jar:/var/agent/atlassian-agent.jar

  jira:
    <<: [*common, *atlassian-env]
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data/jira:/var/jira
      - ./jira/server.xml:/opt/jira/conf/server.xml
      - ./jira/setenv.sh:/opt/jira/bin/setenv.sh
      - ./jira/atlassian-agent.jar:/var/agent/atlassian-agent.jar

  postgresql:
    <<: *common
    image: bitnami/postgresql:16.4.0
    ports:
      - "5432:5432"
    shm_size: 1g
    environment:
      - POSTGRESQL_SHARED_PRELOAD_LIBRARIES=pg_stat_statements
      - POSTGRESQL_PASSWORD=examplepassword
    volumes:
      - './data/postgresql:/bitnami/postgresql/data'
    

