x-common: &common
  restart: always
  logging:
    options:
      max-size: "1m"
      max-file: "1"
  environment:
  - TZ=Asia/Bangkok
  - JVM_MINIMUM_MEMORY=2g
  - JVM_MAXIMUM_MEMORY=4g

services:
  confluence:
    <<: [*common]
    build: .
    ports:
      - "8090:8090"
    volumes:
      - ./data/confluence:/var/confluence
      - ./confluence/server.xml:/opt/confluence/conf/server.xml
      - ./confluence/setenv.sh:/opt/confluence/bin/setenv.sh
      # - ./atlassian-agent.jar:/var/agent/atlassian-agent.jar

  jira:
    <<: [*common]
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data/jira:/var/jira
      - ./jira/server.xml:/opt/jira/conf/server.xml
      - ./jira/setenv.sh:/opt/jira/bin/setenv.sh
      # - ./atlassian-agent.jar:/var/agent/atlassian-agent.jar
