name: build-images

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out
    
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build Confluence Docker image
        with:
          image: ${{ github.repository }}/confluence
          registry: docker.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: confluence/Dockerfile

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build Jira Docker image
        with:
          image: ${{ github.repository }}/jira
          registry: docker.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: jira/Dockerfile
