name: build-docker

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  confluence:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: CI/CD Variables
        id: vars
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            echo "image_tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "image_tag=main-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          fi

      - name: Build Confluence Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./confluence
          push: true
          tags: ${{ github.actor }}/confluence:${{ steps.vars.outputs.image_tag }}
          cache-from: type=registry,ref=${{ github.actor }}/confluence:buildcache
          cache-to: type=registry,ref=${{ github.actor }}/confluence:buildcache,mode=max

  jira:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out

      - name: CI/CD Variables
        id: vars
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            echo "image_tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "image_tag=main-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Jira Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./jira
          push: true
          tags: ${{ github.actor }}/jira:${{ steps.vars.outputs.image_tag }}
          cache-from: type=registry,ref=${{ github.actor }}/jira:buildcache
          cache-to: type=registry,ref=${{ github.actor }}/jira:buildcache,mode=max

