name: build-docker

on:
  push:
    tags:
      - 'v*'

jobs:
  docker-build:
    strategy:
      matrix:
        service: [confluence, jira]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check out

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build ${{ matrix.service }} Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.service }}
          push: true
          tags: ${{ github.actor }}/${{ matrix.service }}:${{ github.ref_name }}
          cache-from: type=registry,ref=${{ github.actor }}/${{ matrix.service }}:buildcache
          cache-to: type=registry,ref=${{ github.actor }}/${{ matrix.service }}:buildcache,mode=max
